window.pokeData = function() {
   var self             = this;
   self.trainers        = [];
   self.pokemon         = [];
   self.equippedPokemon = [];
   self.caughtPokemon   = [];
   self.friends         = [];
   self.friendRequests  = [];
   self.items           = [];
   self.money           = 0;
   self.labPokemon      = [];
   self.labToken        = false;
   self.shopToken       = false;
   self.pokemonList     = [
      {'id': 1, 'name': 'Bulbasaur', 'rarity': 'Super Rare'},
      {'id': 2, 'name': 'Ivysaur', 'rarity': 'Unknown'},
      {'id': 3, 'name': 'Venusaur', 'rarity': 'Unknown'},
      {'id': 4, 'name': 'Charmander', 'rarity': 'Super Rare'},
      {'id': 5, 'name': 'Charmeleon', 'rarity': 'Unknown'},
      {'id': 6, 'name': 'Charizard', 'rarity': 'Unknown'},
      {'id': 7, 'name': 'Squirtle', 'rarity': 'Super Rare'},
      {'id': 8, 'name': 'Wartortle', 'rarity': 'Unknown'},
      {'id': 9, 'name': 'Blastoise', 'rarity': 'Unknown'},
      {'id': 10, 'name': 'Caterpie', 'rarity': 'Very Common'},
      {'id': 11, 'name': 'Metapod', 'rarity': 'Unknown'},
      {'id': 12, 'name': 'Butterfree', 'rarity': 'Common'},
      {'id': 13, 'name': 'Weedle', 'rarity': 'Very Common'},
      {'id': 14, 'name': 'Kakuna', 'rarity': 'Unknown'},
      {'id': 15, 'name': 'Beedrill', 'rarity': 'Common'},
      {'id': 16, 'name': 'Pidgey', 'rarity': 'Very Common'},
      {'id': 17, 'name': 'Pidgeotto', 'rarity': 'Unknown'},
      {'id': 18, 'name': 'Pidgeot', 'rarity': 'Unknown'},
      {'id': 19, 'name': 'Rattata', 'rarity': 'Very Common'},
      {'id': 20, 'name': 'Raticate', 'rarity': 'Unknown'},
      {'id': 21, 'name': 'Spearow', 'rarity': 'Common'},
      {'id': 22, 'name': 'Fearow', 'rarity': 'Unknown'},
      {'id': 23, 'name': 'Ekans', 'rarity': 'Common'},
      {'id': 24, 'name': 'Arbok', 'rarity': 'Unknown'},
      {'id': 25, 'name': 'Pikachu', 'rarity': 'Unknown'},
      {'id': 26, 'name': 'Raichu', 'rarity': 'Unknown'},
      {'id': 27, 'name': 'Sandshrew', 'rarity': 'Common'},
      {'id': 28, 'name': 'Sandslash', 'rarity': 'Unknown'},
      {'id': 29, 'name': 'Nidoran', 'rarity': 'Common'},
      {'id': 30, 'name': 'Nidorina', 'rarity': 'Unknown'},
      {'id': 31, 'name': 'Nidoqueen', 'rarity': 'Unknown'},
      {'id': 32, 'name': 'Nidoran', 'rarity': 'Common'},
      {'id': 33, 'name': 'Nidorino', 'rarity': 'Unknown'},
      {'id': 34, 'name': 'Nidoking', 'rarity': 'Unknown'},
      {'id': 35, 'name': 'Clefairy', 'rarity': 'Rare'},
      {'id': 36, 'name': 'Clefable', 'rarity': 'Unknown'},
      {'id': 37, 'name': 'Vulpix', 'rarity': 'Rare'},
      {'id': 38, 'name': 'Ninetales', 'rarity': 'Unknown'},
      {'id': 39, 'name': 'Jigglypuff', 'rarity': 'Rare'},
      {'id': 40, 'name': 'Wigglytuff', 'rarity': 'Unknown'},
      {'id': 41, 'name': 'Zubat', 'rarity': 'Very Common'},
      {'id': 42, 'name': 'Golbat', 'rarity': 'Unknown'},
      {'id': 43, 'name': 'Oddish', 'rarity': 'Common'},
      {'id': 44, 'name': 'Gloom', 'rarity': 'Unknown'},
      {'id': 45, 'name': 'Vileplume', 'rarity': 'Unknown'},
      {'id': 46, 'name': 'Paras', 'rarity': 'Rare'},
      {'id': 47, 'name': 'Parasect', 'rarity': 'Unknown'},
      {'id': 48, 'name': 'Venonat', 'rarity': 'Common'},
      {'id': 49, 'name': 'Venomoth', 'rarity': 'Unknown'},
      {'id': 50, 'name': 'Diglett', 'rarity': 'Rare'},
      {'id': 51, 'name': 'Dugtrio', 'rarity': 'Unknown'},
      {'id': 52, 'name': 'Meowth', 'rarity': 'Common'},
      {'id': 53, 'name': 'Persian', 'rarity': 'Unknown'},
      {'id': 54, 'name': 'Psyduck', 'rarity': 'Common'},
      {'id': 55, 'name': 'Golduck', 'rarity': 'Unknown'},
      {'id': 56, 'name': 'Mankey', 'rarity': 'Very Rare'},
      {'id': 57, 'name': 'Primeape', 'rarity': 'Unknown'},
      {'id': 58, 'name': 'Growlithe', 'rarity': 'Common'},
      {'id': 59, 'name': 'Arcanine', 'rarity': 'Unknown'},
      {'id': 60, 'name': 'Poliwag', 'rarity': 'Rare'},
      {'id': 61, 'name': 'Poliwhirl', 'rarity': 'Unknown'},
      {'id': 62, 'name': 'Poliwrath', 'rarity': 'Unknown'},
      {'id': 63, 'name': 'Abra', 'rarity': 'Very Rare'},
      {'id': 64, 'name': 'Kadabra', 'rarity': 'Unknown'},
      {'id': 65, 'name': 'Alakazam', 'rarity': 'Unknown'},
      {'id': 66, 'name': 'Machop', 'rarity': 'Very Rare'},
      {'id': 67, 'name': 'Machoke', 'rarity': 'Unknown'},
      {'id': 68, 'name': 'Machamp', 'rarity': 'Unknown'},
      {'id': 69, 'name': 'Bellsprout', 'rarity': 'Common'},
      {'id': 70, 'name': 'Weepinbell', 'rarity': 'Unknown'},
      {'id': 71, 'name': 'Victreebel', 'rarity': 'Unknown'},
      {'id': 72, 'name': 'Tentacool', 'rarity': 'Common'},
      {'id': 73, 'name': 'Tentacruel', 'rarity': 'Unknown'},
      {'id': 74, 'name': 'Geodude', 'rarity': 'Common'},
      {'id': 75, 'name': 'Graveler', 'rarity': 'Unknown'},
      {'id': 76, 'name': 'Golem', 'rarity': 'Unknown'},
      {'id': 77, 'name': 'Ponyta', 'rarity': 'Rare'},
      {'id': 78, 'name': 'Rapidash', 'rarity': 'Unknown'},
      {'id': 79, 'name': 'Slowpoke', 'rarity': 'Very Rare'},
      {'id': 80, 'name': 'Slowbro', 'rarity': 'Unknown'},
      {'id': 81, 'name': 'Magnemite', 'rarity': 'Rare'},
      {'id': 82, 'name': 'Magneton', 'rarity': 'Unknown'},
      {'id': 83, 'name': 'Farfetchd', 'rarity': 'Rare'},
      {'id': 84, 'name': 'Doduo', 'rarity': 'Common'},
      {'id': 85, 'name': 'Dodrio', 'rarity': 'Unknown'},
      {'id': 86, 'name': 'Seel', 'rarity': 'Very Rare'},
      {'id': 87, 'name': 'Dewgong', 'rarity': 'Unknown'},
      {'id': 88, 'name': 'Grimer', 'rarity': 'Very Rare'},
      {'id': 89, 'name': 'Muk', 'rarity': 'Unknown'},
      {'id': 90, 'name': 'Shellder', 'rarity': 'Rare'},
      {'id': 91, 'name': 'Cloyster', 'rarity': 'Unknown'},
      {'id': 92, 'name': 'Gastly', 'rarity': 'Rare'},
      {'id': 93, 'name': 'Haunter', 'rarity': 'Unknown'},
      {'id': 94, 'name': 'Gengar', 'rarity': 'Unknown'},
      {'id': 95, 'name': 'Onix', 'rarity': 'Very Rare'},
      {'id': 96, 'name': 'Drowzee', 'rarity': 'Rare'},
      {'id': 97, 'name': 'Hypno', 'rarity': 'Unknown'},
      {'id': 98, 'name': 'Krabby', 'rarity': 'Rare'},
      {'id': 99, 'name': 'Kingler', 'rarity': 'Unknown'},
      {'id': 100, 'name': 'Voltorb', 'rarity': 'Rare'},
      {'id': 101, 'name': 'Electrode', 'rarity': 'Unknown'},
      {'id': 102, 'name': 'Exeggcute', 'rarity': 'Common'},
      {'id': 103, 'name': 'Exeggutor', 'rarity': 'Unknown'},
      {'id': 104, 'name': 'Cubone', 'rarity': 'Rare'},
      {'id': 105, 'name': 'Marowak', 'rarity': 'Unknown'},
      {'id': 106, 'name': 'Hitmonlee', 'rarity': 'Unknown'},
      {'id': 107, 'name': 'Hitmonchan', 'rarity': 'Unknown'},
      {'id': 108, 'name': 'Lickitung', 'rarity': 'Very Rare'},
      {'id': 109, 'name': 'Koffing', 'rarity': 'Common'},
      {'id': 110, 'name': 'Weezing', 'rarity': 'Unknown'},
      {'id': 111, 'name': 'Rhyhorn', 'rarity': 'Very Rare'},
      {'id': 112, 'name': 'Rhydon', 'rarity': 'Unknown'},
      {'id': 113, 'name': 'Chansey', 'rarity': 'Unknown'},
      {'id': 114, 'name': 'Tangela', 'rarity': 'Very Rare'},
      {'id': 115, 'name': 'Kangaskhan', 'rarity': 'Very Rare'},
      {'id': 116, 'name': 'Horsea', 'rarity': 'Rare'},
      {'id': 117, 'name': 'Seadra', 'rarity': 'Unknown'},
      {'id': 118, 'name': 'Goldeen', 'rarity': 'Rare'},
      {'id': 119, 'name': 'Seaking', 'rarity': 'Unknown'},
      {'id': 120, 'name': 'Staryu', 'rarity': 'Rare'},
      {'id': 121, 'name': 'Starmie', 'rarity': 'Unknown'},
      {'id': 122, 'name': 'Mr-Mime', 'rarity': 'Common'},
      {'id': 123, 'name': 'Scyther', 'rarity': 'Very Rare'},
      {'id': 124, 'name': 'Jynx', 'rarity': 'Rare'},
      {'id': 125, 'name': 'Electabuzz', 'rarity': 'Very Rare'},
      {'id': 126, 'name': 'Magmar', 'rarity': 'Very Rare'},
      {'id': 127, 'name': 'Pinsir', 'rarity': 'Very Rare'},
      {'id': 128, 'name': 'Tauros', 'rarity': 'Very Rare'},
      {'id': 129, 'name': 'Magikarp', 'rarity': 'Super Common'},
      {'id': 130, 'name': 'Gyarados', 'rarity': 'Unknown'},
      {'id': 131, 'name': 'Lapras', 'rarity': 'Very Rare'},
      {'id': 132, 'name': 'Ditto', 'rarity': 'Super Rare'},
      {'id': 133, 'name': 'Eevee', 'rarity': 'Very Rare'},
      {'id': 134, 'name': 'Vaporeon', 'rarity': 'Unknown'},
      {'id': 135, 'name': 'Jolteon', 'rarity': 'Unknown'},
      {'id': 136, 'name': 'Flareon', 'rarity': 'Unknown'},
      {'id': 137, 'name': 'Porygon', 'rarity': 'Super Rare'},
      {'id': 138, 'name': 'Omanyte', 'rarity': 'Super Rare'},
      {'id': 139, 'name': 'Omastar', 'rarity': 'Unknown'},
      {'id': 140, 'name': 'Kabuto', 'rarity': 'Super Rare'},
      {'id': 141, 'name': 'Kabutops', 'rarity': 'Unknown'},
      {'id': 142, 'name': 'Aerodactyl', 'rarity': 'Very Rare'},
      {'id': 143, 'name': 'Snorlax', 'rarity': 'Very Rare'},
      {'id': 144, 'name': 'Articuno', 'rarity': 'Unknown'},
      {'id': 145, 'name': 'Zapdos', 'rarity': 'Unknown'},
      {'id': 146, 'name': 'Moltres', 'rarity': 'Unknown'},
      {'id': 147, 'name': 'Dratini', 'rarity': 'Uber Rare'},
      {'id': 148, 'name': 'Dragonair', 'rarity': 'Unknown'},
      {'id': 149, 'name': 'Dragonite', 'rarity': 'Unknown'},
      {'id': 150, 'name': 'Mewtwo', 'rarity': 'Unknown'},
      {'id': 151, 'name': 'Mew', 'rarity': 'Unknown'},
      {'id': 152, 'name': 'Chikorita', 'rarity': 'Super Rare'},
      {'id': 153, 'name': 'Bayleef', 'rarity': 'Unknown'},
      {'id': 154, 'name': 'Meganium', 'rarity': 'Unknown'},
      {'id': 155, 'name': 'Cyndaquil', 'rarity': 'Super Rare'},
      {'id': 156, 'name': 'Quilava', 'rarity': 'Unknown'},
      {'id': 157, 'name': 'Typhlosion', 'rarity': 'Unknown'},
      {'id': 158, 'name': 'Totodile', 'rarity': 'Super Rare'},
      {'id': 159, 'name': 'Croconaw', 'rarity': 'Unknown'},
      {'id': 160, 'name': 'Feraligatr', 'rarity': 'Unknown'},
      {'id': 161, 'name': 'Sentret', 'rarity': 'Very Common'},
      {'id': 162, 'name': 'Furret', 'rarity': 'Rare'},
      {'id': 163, 'name': 'Hoothoot', 'rarity': 'Very Common'},
      {'id': 164, 'name': 'Noctowl', 'rarity': 'Unknown'},
      {'id': 165, 'name': 'Ledyba', 'rarity': 'Common'},
      {'id': 166, 'name': 'Ledian', 'rarity': 'Unknown'},
      {'id': 167, 'name': 'Spinarak', 'rarity': 'Rare'},
      {'id': 168, 'name': 'Ariados', 'rarity': 'Unknown'},
      {'id': 169, 'name': 'Crobat', 'rarity': 'Unknown'},
      {'id': 170, 'name': 'Chinchou', 'rarity': 'Very Common'},
      {'id': 171, 'name': 'Lanturn', 'rarity': 'Unknown'},
      {'id': 172, 'name': 'Pichu', 'rarity': 'Very Rare'},
      {'id': 173, 'name': 'Cleffa', 'rarity': 'Very Rare'},
      {'id': 174, 'name': 'Igglybuff', 'rarity': 'Very Rare'},
      {'id': 175, 'name': 'Togepi', 'rarity': 'Very Rare'},
      {'id': 176, 'name': 'Togetic', 'rarity': 'Unknown'},
      {'id': 177, 'name': 'Natu', 'rarity': 'Very Rare'},
      {'id': 178, 'name': 'Xatu', 'rarity': 'Unknown'},
      {'id': 179, 'name': 'Mareep', 'rarity': 'Rare'},
      {'id': 180, 'name': 'Flaaffy', 'rarity': 'Rare'},
      {'id': 181, 'name': 'Ampharos', 'rarity': 'Unknown'},
      {'id': 182, 'name': 'Bellossom', 'rarity': 'Unknown'},
      {'id': 183, 'name': 'Marill', 'rarity': 'Unknown'},
      {'id': 184, 'name': 'Azumarill', 'rarity': 'Unknown'},
      {'id': 185, 'name': 'Sudowoodo', 'rarity': 'Common'},
      {'id': 186, 'name': 'Politoed', 'rarity': 'Unknown'},
      {'id': 187, 'name': 'Hoppip', 'rarity': 'Rare'},
      {'id': 188, 'name': 'Skiploom', 'rarity': 'Unknown'},
      {'id': 189, 'name': 'Jumpluff', 'rarity': 'Unknown'},
      {'id': 190, 'name': 'Aipom', 'rarity': 'Common'},
      {'id': 191, 'name': 'Sunkern', 'rarity': 'Rare'},
      {'id': 192, 'name': 'Sunflora', 'rarity': 'Unknown'},
      {'id': 193, 'name': 'Yanma', 'rarity': 'Common'},
      {'id': 194, 'name': 'Wooper', 'rarity': 'Common'},
      {'id': 195, 'name': 'Quagsire', 'rarity': 'Unknown'},
      {'id': 196, 'name': 'Espeon', 'rarity': 'Unknown'},
      {'id': 197, 'name': 'Umbreon', 'rarity': 'Unknown'},
      {'id': 198, 'name': 'Murkrow', 'rarity': 'Rare'},
      {'id': 199, 'name': 'Slowking', 'rarity': 'Unknown'},
      {'id': 200, 'name': 'Misdreavus', 'rarity': 'Very Rare'},
      {'id': 201, 'name': 'Unown', 'rarity': 'Rare'},
      {'id': 202, 'name': 'Wobbuffet', 'rarity': 'Rare'},
      {'id': 203, 'name': 'Girafarig', 'rarity': 'Very Rare'},
      {'id': 204, 'name': 'Pineco', 'rarity': 'Common'},
      {'id': 205, 'name': 'Forretress', 'rarity': 'Unknown'},
      {'id': 206, 'name': 'Dunsparce', 'rarity': 'Common'},
      {'id': 207, 'name': 'Gligar', 'rarity': 'Very Rare'},
      {'id': 208, 'name': 'Steelix', 'rarity': 'Unknown'},
      {'id': 209, 'name': 'Snubbull', 'rarity': 'Common'},
      {'id': 210, 'name': 'Granbull', 'rarity': 'Unknown'},
      {'id': 211, 'name': 'Qwilfish', 'rarity': 'Very Rare'},
      {'id': 212, 'name': 'Scizor', 'rarity': 'Unknown'},
      {'id': 213, 'name': 'Shuckle', 'rarity': 'Very Rare'},
      {'id': 214, 'name': 'Heracross', 'rarity': 'Very Rare'},
      {'id': 215, 'name': 'Sneasel', 'rarity': 'Very Rare'},
      {'id': 216, 'name': 'Teddiursa', 'rarity': 'Rare'},
      {'id': 217, 'name': 'Ursaring', 'rarity': 'Unknown'},
      {'id': 218, 'name': 'Slugma', 'rarity': 'Rare'},
      {'id': 219, 'name': 'Magcargo', 'rarity': 'Unknown'},
      {'id': 220, 'name': 'Swinub', 'rarity': 'Common'},
      {'id': 221, 'name': 'Piloswine', 'rarity': 'Unknown'},
      {'id': 222, 'name': 'Corsola', 'rarity': 'Rare'},
      {'id': 223, 'name': 'Remoraid', 'rarity': 'Rare'},
      {'id': 224, 'name': 'Octillery', 'rarity': 'Unknown'},
      {'id': 225, 'name': 'Delibird', 'rarity': 'Common'},
      {'id': 226, 'name': 'Mantine', 'rarity': 'Common'},
      {'id': 227, 'name': 'Skarmory', 'rarity': 'Very Rare'},
      {'id': 228, 'name': 'Houndour', 'rarity': 'Common'},
      {'id': 229, 'name': 'Houndoom', 'rarity': 'Unknown'},
      {'id': 230, 'name': 'Kingdra', 'rarity': 'Unknown'},
      {'id': 231, 'name': 'Phanpy', 'rarity': 'Common'},
      {'id': 232, 'name': 'Donphan', 'rarity': 'Unknown'},
      {'id': 233, 'name': 'Porygon2', 'rarity': 'Unknown'},
      {'id': 234, 'name': 'Stantler', 'rarity': 'Very Rare'},
      {'id': 235, 'name': 'Smeargle', 'rarity': 'Rare'},
      {'id': 236, 'name': 'Tyrogue', 'rarity': 'Very Rare'},
      {'id': 237, 'name': 'Hitmontop', 'rarity': 'Unknown'},
      {'id': 238, 'name': 'Smoochum', 'rarity': 'Rare'},
      {'id': 239, 'name': 'Elekid', 'rarity': 'Rare'},
      {'id': 240, 'name': 'Magby', 'rarity': 'Rare'},
      {'id': 241, 'name': 'Miltank', 'rarity': 'Very Rare'},
      {'id': 242, 'name': 'Blissey', 'rarity': 'Unknown'},
      {'id': 243, 'name': 'Raikou', 'rarity': 'Unknown'},
      {'id': 244, 'name': 'Entei', 'rarity': 'Unknown'},
      {'id': 245, 'name': 'Suicune', 'rarity': 'Unknown'},
      {'id': 246, 'name': 'Larvitar', 'rarity': 'Uber Rare'},
      {'id': 247, 'name': 'Pupitar', 'rarity': 'Unknown'},
      {'id': 248, 'name': 'Tyranitar', 'rarity': 'Unknown'},
      {'id': 249, 'name': 'Lugia', 'rarity': 'Unknown'},
      {'id': 250, 'name': 'Ho-Oh', 'rarity': 'Unknown'},
      {'id': 251, 'name': 'Celebi', 'rarity': 'Unknown'},
      {'id': 252, 'name': 'Treecko', 'rarity': 'Super Rare'},
      {'id': 253, 'name': 'Grovyle', 'rarity': 'Unknown'},
      {'id': 254, 'name': 'Sceptile', 'rarity': 'Unknown'},
      {'id': 255, 'name': 'Torchic', 'rarity': 'Super Rare'},
      {'id': 256, 'name': 'Combusken', 'rarity': 'Unknown'},
      {'id': 257, 'name': 'Blaziken', 'rarity': 'Unknown'},
      {'id': 258, 'name': 'Mudkip', 'rarity': 'Super Rare'},
      {'id': 259, 'name': 'Marshtomp', 'rarity': 'Unknown'},
      {'id': 260, 'name': 'Swampert', 'rarity': 'Unknown'},
      {'id': 261, 'name': 'Poochyena', 'rarity': 'Very Common'},
      {'id': 262, 'name': 'Mightyena', 'rarity': 'Unknown'},
      {'id': 263, 'name': 'Zigzagoon', 'rarity': 'Very Common'},
      {'id': 264, 'name': 'Linoone', 'rarity': 'Unknown'},
      {'id': 265, 'name': 'Wurmple', 'rarity': 'Very Common'},
      {'id': 266, 'name': 'Silcoon', 'rarity': 'Rare'},
      {'id': 267, 'name': 'Beautifly', 'rarity': 'Very Rare'},
      {'id': 268, 'name': 'Cascoon', 'rarity': 'Rare'},
      {'id': 269, 'name': 'Dustox', 'rarity': 'Very Rare'},
      {'id': 270, 'name': 'Lotad', 'rarity': 'Common'},
      {'id': 271, 'name': 'Lombre', 'rarity': 'Common'},
      {'id': 272, 'name': 'Ludicolo', 'rarity': 'Unknown'},
      {'id': 273, 'name': 'Seedot', 'rarity': 'Common'},
      {'id': 274, 'name': 'Nuzleaf', 'rarity': 'Rare'},
      {'id': 275, 'name': 'Shiftry', 'rarity': 'Unknown'},
      {'id': 276, 'name': 'Taillow', 'rarity': 'Common'},
      {'id': 277, 'name': 'Swellow', 'rarity': 'Unknown'},
      {'id': 278, 'name': 'Wingull', 'rarity': 'Common'},
      {'id': 279, 'name': 'Pelipper', 'rarity': 'Unknown'},
      {'id': 280, 'name': 'Ralts', 'rarity': 'Common'},
      {'id': 281, 'name': 'Kirlia', 'rarity': 'Unknown'},
      {'id': 282, 'name': 'Gardevoir', 'rarity': 'Unknown'},
      {'id': 283, 'name': 'Surskit', 'rarity': 'Common'},
      {'id': 284, 'name': 'Masquerain', 'rarity': 'Unknown'},
      {'id': 285, 'name': 'Shroomish', 'rarity': 'Rare'},
      {'id': 286, 'name': 'Breloom', 'rarity': 'Unknown'},
      {'id': 287, 'name': 'Slakoth', 'rarity': 'Common'},
      {'id': 288, 'name': 'Vigoroth', 'rarity': 'Unknown'},
      {'id': 289, 'name': 'Slaking', 'rarity': 'Unknown'},
      {'id': 290, 'name': 'Nincada', 'rarity': 'Rare'},
      {'id': 291, 'name': 'Ninjask', 'rarity': 'Unknown'},
      {'id': 292, 'name': 'Shedinja', 'rarity': 'Unknown'},
      {'id': 293, 'name': 'Whismur', 'rarity': 'Rare'},
      {'id': 294, 'name': 'Loudred', 'rarity': 'Unknown'},
      {'id': 295, 'name': 'Exploud', 'rarity': 'Unknown'},
      {'id': 296, 'name': 'Makuhita', 'rarity': 'Rare'},
      {'id': 297, 'name': 'Hariyama', 'rarity': 'Unknown'},
      {'id': 298, 'name': 'Azurill', 'rarity': 'Rare'},
      {'id': 299, 'name': 'Nosepass', 'rarity': 'Rare'},
      {'id': 300, 'name': 'Skitty', 'rarity': 'Rare'},
      {'id': 301, 'name': 'Delcatty', 'rarity': 'Unknown'},
      {'id': 302, 'name': 'Sableye', 'rarity': 'Very Rare'},
      {'id': 303, 'name': 'Mawile', 'rarity': 'Very Rare'},
      {'id': 304, 'name': 'Aron', 'rarity': 'Rare'},
      {'id': 305, 'name': 'Lairon', 'rarity': 'Unknown'},
      {'id': 306, 'name': 'Aggron', 'rarity': 'Unknown'},
      {'id': 307, 'name': 'Meditite', 'rarity': 'Very Rare'},
      {'id': 308, 'name': 'Medicham', 'rarity': 'Unknown'},
      {'id': 309, 'name': 'Electrike', 'rarity': 'Rare'},
      {'id': 310, 'name': 'Manectric', 'rarity': 'Unknown'},
      {'id': 311, 'name': 'Plusle', 'rarity': 'Rare'},
      {'id': 312, 'name': 'Minun', 'rarity': 'Rare'},
      {'id': 313, 'name': 'Volbeat', 'rarity': 'Rare'},
      {'id': 314, 'name': 'Illumise', 'rarity': 'Rare'},
      {'id': 315, 'name': 'Roselia', 'rarity': 'Rare'},
      {'id': 316, 'name': 'Gulpin', 'rarity': 'Rare'},
      {'id': 317, 'name': 'Swalot', 'rarity': 'Unknown'},
      {'id': 318, 'name': 'Carvanha', 'rarity': 'Rare'},
      {'id': 319, 'name': 'Sharpedo', 'rarity': 'Unknown'},
      {'id': 320, 'name': 'Wailmer', 'rarity': 'Rare'},
      {'id': 321, 'name': 'Wailord', 'rarity': 'Unknown'},
      {'id': 322, 'name': 'Numel', 'rarity': 'Rare'},
      {'id': 323, 'name': 'Camerupt', 'rarity': 'Unknown'},
      {'id': 324, 'name': 'Torkoal', 'rarity': 'Very Rare'},
      {'id': 325, 'name': 'Spoink', 'rarity': 'Common'},
      {'id': 326, 'name': 'Grumpig', 'rarity': 'Unknown'},
      {'id': 327, 'name': 'Spinda', 'rarity': 'Common'},
      {'id': 328, 'name': 'Trapinch', 'rarity': 'Rare'},
      {'id': 329, 'name': 'Vibrava', 'rarity': 'Unknown'},
      {'id': 330, 'name': 'Flygon', 'rarity': 'Unknown'},
      {'id': 331, 'name': 'Cacnea', 'rarity': 'Common'},
      {'id': 332, 'name': 'Cacturne', 'rarity': 'Unknown'},
      {'id': 333, 'name': 'Swablu', 'rarity': 'Very Rare'},
      {'id': 334, 'name': 'Altaria', 'rarity': 'Unknown'},
      {'id': 335, 'name': 'Zangoose', 'rarity': 'Very Rare'},
      {'id': 336, 'name': 'Seviper', 'rarity': 'Very Rare'},
      {'id': 337, 'name': 'Lunatone', 'rarity': 'Very Rare'},
      {'id': 338, 'name': 'Solrock', 'rarity': 'Very Rare'},
      {'id': 339, 'name': 'Barboach', 'rarity': 'Rare'},
      {'id': 340, 'name': 'Whiscash', 'rarity': 'Unknown'},
      {'id': 341, 'name': 'Corphish', 'rarity': 'Common'},
      {'id': 342, 'name': 'Crawdaunt', 'rarity': 'Unknown'},
      {'id': 343, 'name': 'Baltoy', 'rarity': 'Rare'},
      {'id': 344, 'name': 'Claydol', 'rarity': 'Unknown'},
      {'id': 345, 'name': 'Lileep', 'rarity': 'Common'},
      {'id': 346, 'name': 'Cradily', 'rarity': 'Unknown'},
      {'id': 347, 'name': 'Anorith', 'rarity': 'Common'},
      {'id': 348, 'name': 'Armaldo', 'rarity': 'Unknown'},
      {'id': 349, 'name': 'Feebas', 'rarity': 'Very Rare'},
      {'id': 350, 'name': 'Milotic', 'rarity': 'Unknown'},
      {'id': 351, 'name': 'Castform', 'rarity': 'Rare'},
      {'id': 352, 'name': 'Kecleon', 'rarity': 'Very Rare'},
      {'id': 353, 'name': 'Shuppet', 'rarity': 'Rare'},
      {'id': 354, 'name': 'Banette', 'rarity': 'Unknown'},
      {'id': 355, 'name': 'Duskull', 'rarity': 'Rare'},
      {'id': 356, 'name': 'Dusclops', 'rarity': 'Unknown'},
      {'id': 357, 'name': 'Tropius', 'rarity': 'Very Rare'},
      {'id': 358, 'name': 'Chimecho', 'rarity': 'Rare'},
      {'id': 359, 'name': 'Absol', 'rarity': 'Very Rare'},
      {'id': 360, 'name': 'Wynaut', 'rarity': 'Rare'},
      {'id': 361, 'name': 'Snorunt', 'rarity': 'Common'},
      {'id': 362, 'name': 'Glalie', 'rarity': 'Unknown'},
      {'id': 363, 'name': 'Spheal', 'rarity': 'Common'},
      {'id': 364, 'name': 'Sealeo', 'rarity': 'Unknown'},
      {'id': 365, 'name': 'Walrein', 'rarity': 'Unknown'},
      {'id': 366, 'name': 'Clamperl', 'rarity': 'Rare'},
      {'id': 367, 'name': 'Huntail', 'rarity': 'Unknown'},
      {'id': 368, 'name': 'Gorebyss', 'rarity': 'Unknown'},
      {'id': 369, 'name': 'Relicanth', 'rarity': 'Very Rare'},
      {'id': 370, 'name': 'Luvdisc', 'rarity': 'Rare'},
      {'id': 371, 'name': 'Bagon', 'rarity': 'Uber Rare'},
      {'id': 372, 'name': 'Shelgon', 'rarity': 'Unknown'},
      {'id': 373, 'name': 'Salamence', 'rarity': 'Unknown'},
      {'id': 374, 'name': 'Beldum', 'rarity': 'Unknown'},
      {'id': 375, 'name': 'Metang', 'rarity': 'Unknown'},
      {'id': 376, 'name': 'Metagross', 'rarity': 'Unknown'},
      {'id': 377, 'name': 'Regirock', 'rarity': 'Uber Rare'},
      {'id': 378, 'name': 'Regice', 'rarity': 'Uber Rare'},
      {'id': 379, 'name': 'Registeel', 'rarity': 'Uber Rare'},
      {'id': 380, 'name': 'Latias', 'rarity': 'Unknown'},
      {'id': 381, 'name': 'Latios', 'rarity': 'Unknown'},
      {'id': 382, 'name': 'Kyogre', 'rarity': 'Unknown'},
      {'id': 383, 'name': 'Groudon', 'rarity': 'Unknown'},
      {'id': 384, 'name': 'Rayquaza', 'rarity': 'Unknown'},
      {'id': 385, 'name': 'Jirachi', 'rarity': 'Unknown'},
      {'id': 386, 'name': 'Deoxys-Normal', 'rarity': 'Unknown'},
      {'id': 387, 'name': 'Turtwig', 'rarity': 'Super Rare'},
      {'id': 388, 'name': 'Grotle', 'rarity': 'Unknown'},
      {'id': 389, 'name': 'Torterra', 'rarity': 'Unknown'},
      {'id': 390, 'name': 'Chimchar', 'rarity': 'Super Rare'},
      {'id': 391, 'name': 'Monferno', 'rarity': 'Unknown'},
      {'id': 392, 'name': 'Infernape', 'rarity': 'Unknown'},
      {'id': 393, 'name': 'Piplup', 'rarity': 'Super Rare'},
      {'id': 394, 'name': 'Prinplup', 'rarity': 'Unknown'},
      {'id': 395, 'name': 'Empoleon', 'rarity': 'Unknown'},
      {'id': 396, 'name': 'Starly', 'rarity': 'Very Common'},
      {'id': 397, 'name': 'Staravia', 'rarity': 'Rare'},
      {'id': 398, 'name': 'Staraptor', 'rarity': 'Unknown'},
      {'id': 399, 'name': 'Bidoof', 'rarity': 'Very Common'},
      {'id': 400, 'name': 'Bibarel', 'rarity': 'Unknown'},
      {'id': 401, 'name': 'Kricketot', 'rarity': 'Common'},
      {'id': 402, 'name': 'Kricketune', 'rarity': 'Unknown'},
      {'id': 403, 'name': 'Shinx', 'rarity': 'Rare'},
      {'id': 404, 'name': 'Luxio', 'rarity': 'Unknown'},
      {'id': 405, 'name': 'Luxray', 'rarity': 'Unknown'},
      {'id': 406, 'name': 'Budew', 'rarity': 'Rare'},
      {'id': 407, 'name': 'Roserade', 'rarity': 'Unknown'},
      {'id': 408, 'name': 'Cranidos', 'rarity': 'Very Rare'},
      {'id': 409, 'name': 'Rampardos', 'rarity': 'Unknown'},
      {'id': 410, 'name': 'Shieldon', 'rarity': 'Very Rare'},
      {'id': 411, 'name': 'Bastiodon', 'rarity': 'Unknown'},
      {'id': 412, 'name': 'Burmy', 'rarity': 'Rare'},
      {'id': 413, 'name': 'Wormadam-Plant', 'rarity': 'Unknown'},
      {'id': 414, 'name': 'Mothim', 'rarity': 'Unknown'},
      {'id': 415, 'name': 'Combee', 'rarity': 'Rare'},
      {'id': 416, 'name': 'Vespiquen', 'rarity': 'Unknown'},
      {'id': 417, 'name': 'Pachirisu', 'rarity': 'Very Rare'},
      {'id': 418, 'name': 'Buizel', 'rarity': 'Very Rare'},
      {'id': 419, 'name': 'Floatzel', 'rarity': 'Unknown'},
      {'id': 420, 'name': 'Cherubi', 'rarity': 'Common'},
      {'id': 421, 'name': 'Cherrim', 'rarity': 'Unknown'},
      {'id': 422, 'name': 'Shellos', 'rarity': 'Rare'},
      {'id': 423, 'name': 'Gastrodon', 'rarity': 'Unknown'},
      {'id': 424, 'name': 'Ambipom', 'rarity': 'Unknown'},
      {'id': 425, 'name': 'Drifloon', 'rarity': 'Very Rare'},
      {'id': 426, 'name': 'Drifblim', 'rarity': 'Unknown'},
      {'id': 427, 'name': 'Buneary', 'rarity': 'Very Rare'},
      {'id': 428, 'name': 'Lopunny', 'rarity': 'Unknown'},
      {'id': 429, 'name': 'Mismagius', 'rarity': 'Unknown'},
      {'id': 430, 'name': 'Honchkrow', 'rarity': 'Unknown'},
      {'id': 431, 'name': 'Glameow', 'rarity': 'Very Rare'},
      {'id': 432, 'name': 'Purugly', 'rarity': 'Unknown'},
      {'id': 433, 'name': 'Chingling', 'rarity': 'Rare'},
      {'id': 434, 'name': 'Stunky', 'rarity': 'Rare'},
      {'id': 435, 'name': 'Skuntank', 'rarity': 'Unknown'},
      {'id': 436, 'name': 'Bronzor', 'rarity': 'Common'},
      {'id': 437, 'name': 'Bronzong', 'rarity': 'Unknown'},
      {'id': 438, 'name': 'Bonsly', 'rarity': 'Rare'},
      {'id': 439, 'name': 'Mime-Jr', 'rarity': 'Very Rare'},
      {'id': 440, 'name': 'Happiny', 'rarity': 'Rare'},
      {'id': 441, 'name': 'Chatot', 'rarity': 'Very Rare'},
      {'id': 442, 'name': 'Spiritomb', 'rarity': 'Very Rare'},
      {'id': 443, 'name': 'Gible', 'rarity': 'Unknown'},
      {'id': 444, 'name': 'Gabite', 'rarity': 'Unknown'},
      {'id': 445, 'name': 'Garchomp', 'rarity': 'Unknown'},
      {'id': 446, 'name': 'Munchlax', 'rarity': 'Very Rare'},
      {'id': 447, 'name': 'Riolu', 'rarity': 'Rare'},
      {'id': 448, 'name': 'Lucario', 'rarity': 'Unknown'},
      {'id': 449, 'name': 'Hippopotas', 'rarity': 'Very Rare'},
      {'id': 450, 'name': 'Hippowdon', 'rarity': 'Unknown'},
      {'id': 451, 'name': 'Skorupi', 'rarity': 'Very Rare'},
      {'id': 452, 'name': 'Drapion', 'rarity': 'Unknown'},
      {'id': 453, 'name': 'Croagunk', 'rarity': 'Rare'},
      {'id': 454, 'name': 'Toxicroak', 'rarity': 'Unknown'},
      {'id': 455, 'name': 'Carnivine', 'rarity': 'Very Rare'},
      {'id': 456, 'name': 'Finneon', 'rarity': 'Rare'},
      {'id': 457, 'name': 'Lumineon', 'rarity': 'Unknown'},
      {'id': 458, 'name': 'Mantyke', 'rarity': 'Very Rare'},
      {'id': 459, 'name': 'Snover', 'rarity': 'Very Rare'},
      {'id': 460, 'name': 'Abomasnow', 'rarity': 'Unknown'},
      {'id': 461, 'name': 'Weavile', 'rarity': 'Unknown'},
      {'id': 462, 'name': 'Magnezone', 'rarity': 'Unknown'},
      {'id': 463, 'name': 'Lickilicky', 'rarity': 'Unknown'},
      {'id': 464, 'name': 'Rhyperior', 'rarity': 'Unknown'},
      {'id': 465, 'name': 'Tangrowth', 'rarity': 'Unknown'},
      {'id': 466, 'name': 'Electivire', 'rarity': 'Unknown'},
      {'id': 467, 'name': 'Magmortar', 'rarity': 'Unknown'},
      {'id': 468, 'name': 'Togekiss', 'rarity': 'Unknown'},
      {'id': 469, 'name': 'Yanmega', 'rarity': 'Unknown'},
      {'id': 470, 'name': 'Leafeon', 'rarity': 'Unknown'},
      {'id': 471, 'name': 'Glaceon', 'rarity': 'Unknown'},
      {'id': 472, 'name': 'Gliscor', 'rarity': 'Unknown'},
      {'id': 473, 'name': 'Mamoswine', 'rarity': 'Unknown'},
      {'id': 474, 'name': 'Porygon-Z', 'rarity': 'Unknown'},
      {'id': 475, 'name': 'Gallade', 'rarity': 'Unknown'},
      {'id': 476, 'name': 'Probopass', 'rarity': 'Unknown'},
      {'id': 477, 'name': 'Dusknoir', 'rarity': 'Unknown'},
      {'id': 478, 'name': 'Froslass', 'rarity': 'Unknown'},
      {'id': 479, 'name': 'Rotom', 'rarity': 'Very Rare'},
      {'id': 480, 'name': 'Uxie', 'rarity': 'Unknown'},
      {'id': 481, 'name': 'Mesprit', 'rarity': 'Unknown'},
      {'id': 482, 'name': 'Azelf', 'rarity': 'Unknown'},
      {'id': 483, 'name': 'Dialga', 'rarity': 'Unknown'},
      {'id': 484, 'name': 'Palkia', 'rarity': 'Unknown'},
      {'id': 485, 'name': 'Heatran', 'rarity': 'Unknown'},
      {'id': 486, 'name': 'Regigigas', 'rarity': 'Unknown'},
      {'id': 487, 'name': 'Giratina-Altered', 'rarity': 'Unknown'},
      {'id': 488, 'name': 'Cresselia', 'rarity': 'Unknown'},
      {'id': 489, 'name': 'Phione', 'rarity': 'Unknown'},
      {'id': 490, 'name': 'Manaphy', 'rarity': 'Unknown'},
      {'id': 491, 'name': 'Darkrai', 'rarity': 'Unknown'},
      {'id': 492, 'name': 'Shaymin-Land', 'rarity': 'Unknown'},
      {'id': 493, 'name': 'Arceus', 'rarity': 'Unknown'},
      {'id': 494, 'name': 'Victini', 'rarity': 'Unknown'},
      {'id': 495, 'name': 'Snivy', 'rarity': 'Super Rare'},
      {'id': 496, 'name': 'Servine', 'rarity': 'Unknown'},
      {'id': 497, 'name': 'Serperior', 'rarity': 'Unknown'},
      {'id': 498, 'name': 'Tepig', 'rarity': 'Super Rare'},
      {'id': 499, 'name': 'Pignite', 'rarity': 'Unknown'},
      {'id': 500, 'name': 'Emboar', 'rarity': 'Unknown'},
      {'id': 501, 'name': 'Oshawott', 'rarity': 'Super Rare'},
      {'id': 502, 'name': 'Dewott', 'rarity': 'Unknown'},
      {'id': 503, 'name': 'Samurott', 'rarity': 'Unknown'},
      {'id': 504, 'name': 'Patrat', 'rarity': 'Rare'},
      {'id': 505, 'name': 'Watchog', 'rarity': 'Unknown'},
      {'id': 506, 'name': 'Lillipup', 'rarity': 'Rare'},
      {'id': 507, 'name': 'Herdier', 'rarity': 'Unknown'},
      {'id': 508, 'name': 'Stoutland', 'rarity': 'Unknown'},
      {'id': 509, 'name': 'Purrloin', 'rarity': 'Rare'},
      {'id': 510, 'name': 'Liepard', 'rarity': 'Unknown'},
      {'id': 511, 'name': 'Pansage', 'rarity': 'Very Rare'},
      {'id': 512, 'name': 'Simisage', 'rarity': 'Unknown'},
      {'id': 513, 'name': 'Pansear', 'rarity': 'Very Rare'},
      {'id': 514, 'name': 'Simisear', 'rarity': 'Unknown'},
      {'id': 515, 'name': 'Panpour', 'rarity': 'Very Rare'},
      {'id': 516, 'name': 'Simipour', 'rarity': 'Unknown'},
      {'id': 517, 'name': 'Munna', 'rarity': 'Rare'},
      {'id': 518, 'name': 'Musharna', 'rarity': 'Unknown'},
      {'id': 519, 'name': 'Pidove', 'rarity': 'Common'},
      {'id': 520, 'name': 'Tranquill', 'rarity': 'Unknown'},
      {'id': 521, 'name': 'Unfezant', 'rarity': 'Unknown'},
      {'id': 522, 'name': 'Blitzle', 'rarity': 'Common'},
      {'id': 523, 'name': 'Zebstrika', 'rarity': 'Unknown'},
      {'id': 524, 'name': 'Roggenrola', 'rarity': 'Rare'},
      {'id': 525, 'name': 'Boldore', 'rarity': 'Unknown'},
      {'id': 526, 'name': 'Gigalith', 'rarity': 'Unknown'},
      {'id': 527, 'name': 'Woobat', 'rarity': 'Very Rare'},
      {'id': 528, 'name': 'Swoobat', 'rarity': 'Unknown'},
      {'id': 529, 'name': 'Drilbur', 'rarity': 'Very Rare'},
      {'id': 530, 'name': 'Excadrill', 'rarity': 'Unknown'},
      {'id': 531, 'name': 'Audino', 'rarity': 'Very Rare'},
      {'id': 532, 'name': 'Timburr', 'rarity': 'Very Rare'},
      {'id': 533, 'name': 'Gurdurr', 'rarity': 'Unknown'},
      {'id': 534, 'name': 'Conkeldurr', 'rarity': 'Unknown'},
      {'id': 535, 'name': 'Tympole', 'rarity': 'Rare'},
      {'id': 536, 'name': 'Palpitoad', 'rarity': 'Unknown'},
      {'id': 537, 'name': 'Seismitoad', 'rarity': 'Unknown'},
      {'id': 538, 'name': 'Throh', 'rarity': 'Very Rare'},
      {'id': 539, 'name': 'Sawk', 'rarity': 'Very Rare'},
      {'id': 540, 'name': 'Sewaddle', 'rarity': 'Rare'},
      {'id': 541, 'name': 'Swadloon', 'rarity': 'Unknown'},
      {'id': 542, 'name': 'Leavanny', 'rarity': 'Unknown'},
      {'id': 543, 'name': 'Venipede', 'rarity': 'Rare'},
      {'id': 544, 'name': 'Whirlipede', 'rarity': 'Unknown'},
      {'id': 545, 'name': 'Scolipede', 'rarity': 'Unknown'},
      {'id': 546, 'name': 'Cottonee', 'rarity': 'Rare'},
      {'id': 547, 'name': 'Whimsicott', 'rarity': 'Unknown'},
      {'id': 548, 'name': 'Petilil', 'rarity': 'Rare'},
      {'id': 549, 'name': 'Lilligant', 'rarity': 'Unknown'},
      {'id': 550, 'name': 'Basculin', 'rarity': 'Very Rare'},
      {'id': 551, 'name': 'Sandile', 'rarity': 'Rare'},
      {'id': 552, 'name': 'Krokorok', 'rarity': 'Unknown'},
      {'id': 553, 'name': 'Krookodile', 'rarity': 'Unknown'},
      {'id': 554, 'name': 'Darumaka', 'rarity': 'Very Rare'},
      {'id': 555, 'name': 'Darmanitan-Standard', 'rarity': 'Unknown'},
      {'id': 556, 'name': 'Maractus', 'rarity': 'Very Rare'},
      {'id': 557, 'name': 'Dwebble', 'rarity': 'Very Rare'},
      {'id': 558, 'name': 'Crustle', 'rarity': 'Unknown'},
      {'id': 559, 'name': 'Scraggy', 'rarity': 'Very Rare'},
      {'id': 560, 'name': 'Scrafty', 'rarity': 'Unknown'},
      {'id': 561, 'name': 'Sigilyph', 'rarity': 'Very Rare'},
      {'id': 562, 'name': 'Yamask', 'rarity': 'Very Rare'},
      {'id': 563, 'name': 'Cofagrigus', 'rarity': 'Unknown'},
      {'id': 564, 'name': 'Tirtouga', 'rarity': 'Very Rare'},
      {'id': 565, 'name': 'Carracosta', 'rarity': 'Unknown'},
      {'id': 566, 'name': 'Archen', 'rarity': 'Very Rare'},
      {'id': 567, 'name': 'Archeops', 'rarity': 'Unknown'},
      {'id': 568, 'name': 'Trubbish', 'rarity': 'Very Rare'},
      {'id': 569, 'name': 'Garbodor', 'rarity': 'Unknown'},
      {'id': 570, 'name': 'Zorua', 'rarity': 'Very Rare'},
      {'id': 571, 'name': 'Zoroark', 'rarity': 'Unknown'},
      {'id': 572, 'name': 'Minccino', 'rarity': 'Rare'},
      {'id': 573, 'name': 'Cinccino', 'rarity': 'Unknown'},
      {'id': 574, 'name': 'Gothita', 'rarity': 'Rare'},
      {'id': 575, 'name': 'Gothorita', 'rarity': 'Unknown'},
      {'id': 576, 'name': 'Gothitelle', 'rarity': 'Unknown'},
      {'id': 577, 'name': 'Solosis', 'rarity': 'Rare'},
      {'id': 578, 'name': 'Duosion', 'rarity': 'Unknown'},
      {'id': 579, 'name': 'Reuniclus', 'rarity': 'Unknown'},
      {'id': 580, 'name': 'Ducklett', 'rarity': 'Very Rare'},
      {'id': 581, 'name': 'Swanna', 'rarity': 'Unknown'},
      {'id': 582, 'name': 'Vanillite', 'rarity': 'Very Rare'},
      {'id': 583, 'name': 'Vanillish', 'rarity': 'Unknown'},
      {'id': 584, 'name': 'Vanilluxe', 'rarity': 'Unknown'},
      {'id': 585, 'name': 'Deerling', 'rarity': 'Very Rare'},
      {'id': 586, 'name': 'Sawsbuck', 'rarity': 'Unknown'},
      {'id': 587, 'name': 'Emolga', 'rarity': 'Very Rare'},
      {'id': 588, 'name': 'Karrablast', 'rarity': 'Very Rare'},
      {'id': 589, 'name': 'Escavalier', 'rarity': 'Unknown'},
      {'id': 590, 'name': 'Foongus', 'rarity': 'Rare'},
      {'id': 591, 'name': 'Amoonguss', 'rarity': 'Unknown'},
      {'id': 592, 'name': 'Frillish', 'rarity': 'Very Rare'},
      {'id': 593, 'name': 'Jellicent', 'rarity': 'Unknown'},
      {'id': 594, 'name': 'Alomomola', 'rarity': 'Very Rare'},
      {'id': 595, 'name': 'Joltik', 'rarity': 'Very Rare'},
      {'id': 596, 'name': 'Galvantula', 'rarity': 'Unknown'},
      {'id': 597, 'name': 'Ferroseed', 'rarity': 'Very Rare'},
      {'id': 598, 'name': 'Ferrothorn', 'rarity': 'Unknown'},
      {'id': 599, 'name': 'Klink', 'rarity': 'Rare'},
      {'id': 600, 'name': 'Klang', 'rarity': 'Unknown'},
      {'id': 601, 'name': 'Klinklang', 'rarity': 'Unknown'},
      {'id': 602, 'name': 'Tynamo', 'rarity': 'Rare'},
      {'id': 603, 'name': 'Eelektrik', 'rarity': 'Unknown'},
      {'id': 604, 'name': 'Eelektross', 'rarity': 'Unknown'},
      {'id': 605, 'name': 'Elgyem', 'rarity': 'Very Rare'},
      {'id': 606, 'name': 'Beheeyem', 'rarity': 'Unknown'},
      {'id': 607, 'name': 'Litwick', 'rarity': 'Rare'},
      {'id': 608, 'name': 'Lampent', 'rarity': 'Unknown'},
      {'id': 609, 'name': 'Chandelure', 'rarity': 'Unknown'},
      {'id': 610, 'name': 'Axew', 'rarity': 'Very Rare'},
      {'id': 611, 'name': 'Fraxure', 'rarity': 'Unknown'},
      {'id': 612, 'name': 'Haxorus', 'rarity': 'Unknown'},
      {'id': 613, 'name': 'Cubchoo', 'rarity': 'Very Rare'},
      {'id': 614, 'name': 'Beartic', 'rarity': 'Unknown'},
      {'id': 615, 'name': 'Cryogonal', 'rarity': 'Very Rare'},
      {'id': 616, 'name': 'Shelmet', 'rarity': 'Very Rare'},
      {'id': 617, 'name': 'Accelgor', 'rarity': 'Unknown'},
      {'id': 618, 'name': 'Stunfisk', 'rarity': 'Very Rare'},
      {'id': 619, 'name': 'Mienfoo', 'rarity': 'Very Rare'},
      {'id': 620, 'name': 'Mienshao', 'rarity': 'Unknown'},
      {'id': 621, 'name': 'Druddigon', 'rarity': 'Very Rare'},
      {'id': 622, 'name': 'Golett', 'rarity': 'Very Rare'},
      {'id': 623, 'name': 'Golurk', 'rarity': 'Unknown'},
      {'id': 624, 'name': 'Pawniard', 'rarity': 'Very Rare'},
      {'id': 625, 'name': 'Bisharp', 'rarity': 'Unknown'},
      {'id': 626, 'name': 'Bouffalant', 'rarity': 'Very Rare'},
      {'id': 627, 'name': 'Rufflet', 'rarity': 'Very Rare'},
      {'id': 628, 'name': 'Braviary', 'rarity': 'Unknown'},
      {'id': 629, 'name': 'Vullaby', 'rarity': 'Very Rare'},
      {'id': 630, 'name': 'Mandibuzz', 'rarity': 'Unknown'},
      {'id': 631, 'name': 'Heatmor', 'rarity': 'Very Rare'},
      {'id': 632, 'name': 'Durant', 'rarity': 'Very Rare'},
      {'id': 633, 'name': 'Deino', 'rarity': 'Unknown'},
      {'id': 634, 'name': 'Zweilous', 'rarity': 'Unknown'},
      {'id': 635, 'name': 'Hydreigon', 'rarity': 'Unknown'},
      {'id': 636, 'name': 'Larvesta', 'rarity': 'Very Rare'},
      {'id': 637, 'name': 'Volcarona', 'rarity': 'Unknown'},
      {'id': 638, 'name': 'Cobalion', 'rarity': 'Unknown'},
      {'id': 639, 'name': 'Terrakion', 'rarity': 'Unknown'},
      {'id': 640, 'name': 'Virizion', 'rarity': 'Unknown'},
      {'id': 641, 'name': 'Tornadus', 'rarity': 'Unknown'},
      {'id': 642, 'name': 'Thundurus', 'rarity': 'Unknown'},
      {'id': 643, 'name': 'Reshiram', 'rarity': 'Unknown'},
      {'id': 644, 'name': 'Zekrom', 'rarity': 'Unknown'},
      {'id': 645, 'name': 'Landorus', 'rarity': 'Unknown'},
      {'id': 646, 'name': 'Kyurem', 'rarity': 'Unknown'},
      {'id': 647, 'name': 'Keldeo', 'rarity': 'Unknown'},
      {'id': 648, 'name': 'Meloetta', 'rarity': 'Unknown'},
      {'id': 649, 'name': 'Genesect', 'rarity': 'Unknown'},
      {'id': 650, 'name': 'Chespin', 'rarity': 'Super Rare'},
      {'id': 651, 'name': 'Quilladin', 'rarity': 'Unknown'},
      {'id': 652, 'name': 'Chesnaught', 'rarity': 'Unknown'},
      {'id': 653, 'name': 'Fennekin', 'rarity': 'Super Rare'},
      {'id': 654, 'name': 'Braixen', 'rarity': 'Unknown'},
      {'id': 655, 'name': 'Delphox', 'rarity': 'Unknown'},
      {'id': 656, 'name': 'Froakie', 'rarity': 'Super Rare'},
      {'id': 657, 'name': 'Frogadier', 'rarity': 'Unknown'},
      {'id': 658, 'name': 'Greninja', 'rarity': 'Unknown'},
      {'id': 659, 'name': 'Bunnelby', 'rarity': 'Rare'},
      {'id': 660, 'name': 'Diggersby', 'rarity': 'Unknown'},
      {'id': 661, 'name': 'Fletchling', 'rarity': 'Rare'},
      {'id': 662, 'name': 'Fletchinder', 'rarity': 'Unknown'},
      {'id': 663, 'name': 'Talonflame', 'rarity': 'Unknown'},
      {'id': 664, 'name': 'Scatterbug', 'rarity': 'Rare'},
      {'id': 665, 'name': 'Spewpa', 'rarity': 'Unknown'},
      {'id': 666, 'name': 'Vivillon', 'rarity': 'Unknown'},
      {'id': 667, 'name': 'Litleo', 'rarity': 'Very Rare'},
      {'id': 668, 'name': 'Pyroar', 'rarity': 'Unknown'},
      {'id': 669, 'name': 'Flabebe', 'rarity': 'Very Rare'},
      {'id': 670, 'name': 'Floette', 'rarity': 'Unknown'},
      {'id': 671, 'name': 'Florges', 'rarity': 'Unknown'},
      {'id': 672, 'name': 'Skiddo', 'rarity': 'Very Rare'},
      {'id': 673, 'name': 'Gogoat', 'rarity': 'Unknown'},
      {'id': 674, 'name': 'Pancham', 'rarity': 'Very Rare'},
      {'id': 675, 'name': 'Pangoro', 'rarity': 'Unknown'},
      {'id': 676, 'name': 'Furfrou', 'rarity': 'Very Rare'},
      {'id': 677, 'name': 'Espurr', 'rarity': 'Very Rare'},
      {'id': 678, 'name': 'Meowstic-Male', 'rarity': 'Unknown'},
      {'id': 679, 'name': 'Honedge', 'rarity': 'Very Rare'},
      {'id': 680, 'name': 'Doublade', 'rarity': 'Unknown'},
      {'id': 681, 'name': 'Aegislash-Shield', 'rarity': 'Unknown'},
      {'id': 682, 'name': 'Spritzee', 'rarity': 'Very Rare'},
      {'id': 683, 'name': 'Aromatisse', 'rarity': 'Unknown'},
      {'id': 684, 'name': 'Swirlix', 'rarity': 'Very Rare'},
      {'id': 685, 'name': 'Slurpuff', 'rarity': 'Unknown'},
      {'id': 686, 'name': 'Inkay', 'rarity': 'Rare'},
      {'id': 687, 'name': 'Malamar', 'rarity': 'Unknown'},
      {'id': 688, 'name': 'Binacle', 'rarity': 'Very Rare'},
      {'id': 689, 'name': 'Barbaracle', 'rarity': 'Unknown'},
      {'id': 690, 'name': 'Skrelp', 'rarity': 'Very Rare'},
      {'id': 691, 'name': 'Dragalge', 'rarity': 'Unknown'},
      {'id': 692, 'name': 'Clauncher', 'rarity': 'Very Rare'},
      {'id': 693, 'name': 'Clawitzer', 'rarity': 'Unknown'},
      {'id': 694, 'name': 'Helioptile', 'rarity': 'Rare'},
      {'id': 695, 'name': 'Heliolisk', 'rarity': 'Unknown'},
      {'id': 696, 'name': 'Tyrunt', 'rarity': 'Very Rare'},
      {'id': 697, 'name': 'Tyrantrum', 'rarity': 'Unknown'},
      {'id': 698, 'name': 'Amaura', 'rarity': 'Very Rare'},
      {'id': 699, 'name': 'Aurorus', 'rarity': 'Unknown'},
      {'id': 700, 'name': 'Sylveon', 'rarity': 'Unknown'},
      {'id': 701, 'name': 'Hawlucha', 'rarity': 'Very Rare'},
      {'id': 702, 'name': 'Dedenne', 'rarity': 'Very Rare'},
      {'id': 703, 'name': 'Carbink', 'rarity': 'Very Rare'},
      {'id': 704, 'name': 'Goomy', 'rarity': 'Unknown'},
      {'id': 705, 'name': 'Sliggoo', 'rarity': 'Unknown'},
      {'id': 706, 'name': 'Goodra', 'rarity': 'Unknown'},
      {'id': 707, 'name': 'Klefki', 'rarity': 'Very Rare'},
      {'id': 708, 'name': 'Phantump', 'rarity': 'Very Rare'},
      {'id': 709, 'name': 'Trevenant', 'rarity': 'Unknown'},
      {'id': 710, 'name': 'Pumpkaboo', 'rarity': 'Very Rare'},
      {'id': 711, 'name': 'Gourgeist', 'rarity': 'Unknown'},
      {'id': 712, 'name': 'Bergmite', 'rarity': 'Very Rare'},
      {'id': 713, 'name': 'Avalugg', 'rarity': 'Unknown'},
      {'id': 714, 'name': 'Noibat', 'rarity': 'Rare'},
      {'id': 715, 'name': 'Noivern', 'rarity': 'Unknown'},
      {'id': 716, 'name': 'Xerneas', 'rarity': 'Unknown'},
      {'id': 717, 'name': 'Yveltal', 'rarity': 'Unknown'},
      {'id': 718, 'name': 'Zygarde', 'rarity': 'Unknown'},
      {'id': 719, 'name': 'Diancie', 'rarity': 'Unknown'},
      {'id': 720, 'name': 'Hoopa', 'rarity': 'Unknown'},
      {'id': 721, 'name': 'Volcanion', 'rarity': 'Unknown'}
   ];
	self.itemList = [
	   {'id': 1,   'name': 'Master Ball',         'price': 100000},
	   {'id': 2,   'name': 'Ultra Ball',          'price': 1200},
	   {'id': 3,   'name': 'Great Ball',          'price': 600},
	   {'id': 4,   'name': 'Poke Ball',           'price': 200},
	   {'id': 17,  'name': 'Potion',              'price': 300},
	   {'id': 18,  'name': 'Antidote',            'price': 100},
	   {'id': 19,  'name': 'Burn Heal',           'price': 250},
	   {'id': 20,  'name': 'Ice Heal',            'price': 250},
	   {'id': 28,  'name': 'Revive',              'price': 1500},
	   {'id': 29,  'name': 'Max Revive',          'price': 4000},
	   {'id': 34,  'name': 'Energy Powder',       'price': 0},
	   {'id': 35,  'name': 'Energy Root',         'price': 0},
	   {'id': 36,  'name': 'Heal Powder',         'price': 0},
	   {'id': 37,  'name': 'Revival Herb',        'price': 0},
	   {'id': 38,  'name': 'Ether',               'price': 0},
	   {'id': 39,  'name': 'Max Ether',           'price': 0},
	   {'id': 40,  'name': 'Elixir',              'price': 0},
	   {'id': 41,  'name': 'Max Elixir',          'price': 0},
	   {'id': 42,  'name': 'Lava Cookie',         'price': 0},
	   {'id': 43,  'name': 'Berry Juice',         'price': 0},
	   {'id': 44,  'name': 'Sacred Ash',          'price': 0},
	   {'id': 45,  'name': 'HP Up',               'price': 0},
	   {'id': 46,  'name': 'Protein',             'price': 0},
	   {'id': 47,  'name': 'Iron',                'price': 0},
	   {'id': 48,  'name': 'Carbos',              'price': 0},
	   {'id': 49,  'name': 'Calcium',             'price': 0},
	   {'id': 51,  'name': 'PP Up',               'price': 0},
	   {'id': 52,  'name': 'Zinc',                'price': 0},
	   {'id': 53,  'name': 'PP Max',              'price': 0},
	   {'id': 54,  'name': 'Old Gateau',          'price': 0},
	   {'id': 55,  'name': 'Guard Spec.',         'price': 0},
	   {'id': 56,  'name': 'Dire Hit',            'price': 0},
	   {'id': 57,  'name': 'X Attack',            'price': 0},
	   {'id': 58,  'name': 'X Defense',           'price': 0},
	   {'id': 59,  'name': 'X Speed',             'price': 0},
	   {'id': 60,  'name': 'X Accuracy',          'price': 0},
	   {'id': 61,  'name': 'X Sp. Atk',           'price': 0},
	   {'id': 62,  'name': 'X Sp. Def',           'price': 0},
	   {'id': 63,  'name': 'Poke Doll',           'price': 0},
	   {'id': 64,  'name': 'Fluffy Tail',         'price': 0},
	   {'id': 65,  'name': 'Blue Flute',          'price': 0},
	   {'id': 66,  'name': 'Yellow Flute',        'price': 0},
	   {'id': 67,  'name': 'Red Flute',           'price': 0},
	   {'id': 68,  'name': 'Black Flute',         'price': 0},
	   {'id': 69,  'name': 'White Flute',         'price': 0},
	   {'id': 70,  'name': 'Shoal Salt',          'price': 0},
	   {'id': 71,  'name': 'Shoal Shell',         'price': 0},
	   {'id': 72,  'name': 'Red Shard',           'price': 0},
	   {'id': 73,  'name': 'Blue Shard',          'price': 0},
	   {'id': 74,  'name': 'Yellow Shard',        'price': 0},
	   {'id': 75,  'name': 'Green Shard',         'price': 0},
	   {'id': 76,  'name': 'Super Repel',         'price': 0},
	   {'id': 77,  'name': 'Max Repel',           'price': 0},
	   {'id': 78,  'name': 'Escape Rope',         'price': 0},
	   {'id': 79,  'name': 'Repel',               'price': 0},
	   {'id': 80,  'name': 'Sun Stone',           'price': 8000},
	   {'id': 81,  'name': 'Moon Stone',          'price': 8000},
	   {'id': 82,  'name': 'Fire Stone',          'price': 8000},
	   {'id': 83,  'name': 'Thunder Stone',       'price': 8000},
	   {'id': 84,  'name': 'Water Stone',         'price': 8000},
	   {'id': 85,  'name': 'Leaf Stone',          'price': 8000},
	   {'id': 81,  'name': 'Moon Stone',          'price': 0},
	   {'id': 84,  'name': 'Water Stone',         'price': 0},
	   {'id': 85,  'name': 'Leaf Stone',          'price': 0},
	   {'id': 86,  'name': 'Tiny Mushroom',       'price': 0},
	   {'id': 87,  'name': 'Big Mushroom',        'price': 0},
	   {'id': 88,  'name': 'Pearl',               'price': 0},
	   {'id': 89,  'name': 'Big Pearl',           'price': 0},
	   {'id': 90,  'name': 'Stardust',            'price': 0},
	   {'id': 91,  'name': 'Star Piece',          'price': 0},
	   {'id': 92,  'name': 'Nugget',              'price': 0},
	   {'id': 93,  'name': 'Heart Scale',         'price': 0},
	   {'id': 94,  'name': 'Honey',               'price': 0},
	   {'id': 95,  'name': 'Growth Mulch',        'price': 0},
	   {'id': 96,  'name': 'Damp Mulch',          'price': 0},
	   {'id': 97,  'name': 'Stable Mulch',        'price': 0},
	   {'id': 98,  'name': 'Gooey Mulch',         'price': 0},
	   {'id': 99,  'name': 'Root Fossil',         'price': 0},
	   {'id': 100, 'name': 'Claw Fossil',         'price': 0},
	   {'id': 101, 'name': 'Helix Fossil',        'price': 0},
	   {'id': 102, 'name': 'Dome Fossil',         'price': 0},
	   {'id': 103, 'name': 'Old Amber',           'price': 0},
	   {'id': 104, 'name': 'Armor Fossil',        'price': 0},
	   {'id': 105, 'name': 'Skull Fossil',        'price': 0},
	   {'id': 106, 'name': 'Rare Bone',           'price': 0},
	   {'id': 107, 'name': 'Shiny Stone',         'price': 8000},
	   {'id': 108, 'name': 'Dusk Stone',          'price': 8000},
	   {'id': 109, 'name': 'Dawn Stone',          'price': 8000},
	   {'id': 110, 'name': 'Oval Stone',          'price': 0},
	   {'id': 111, 'name': 'Odd Keystone',        'price': 0},
	   {'id': 112, 'name': 'Adamant Orb',         'price': 0},
	   {'id': 113, 'name': 'Lustrous Orb',        'price': 0},
	   {'id': 114, 'name': 'Grass Mail',          'price': 0},
	   {'id': 115, 'name': 'Flame Mail',          'price': 0},
	   {'id': 116, 'name': 'Bubble Mail',         'price': 0},
	   {'id': 117, 'name': 'Bloom Mail',          'price': 0},
	   {'id': 118, 'name': 'Tunnel Mail',         'price': 0},
	   {'id': 119, 'name': 'Steel Mail',          'price': 0},
	   {'id': 120, 'name': 'Heart Mail',          'price': 0},
	   {'id': 121, 'name': 'Snow Mail',           'price': 0},
	   {'id': 122, 'name': 'Space Mail',          'price': 0},
	   {'id': 123, 'name': 'Air Mail',            'price': 0},
	   {'id': 124, 'name': 'Mosaic Mail',         'price': 0},
	   {'id': 125, 'name': 'Brick Mail',          'price': 0},
	   {'id': 126, 'name': 'Cheri Berry',         'price': 0},
	   {'id': 127, 'name': 'Chesto Berry',        'price': 0},
	   {'id': 128, 'name': 'Pecha Berry',         'price': 0},
	   {'id': 129, 'name': 'Rawst Berry',         'price': 0},
	   {'id': 130, 'name': 'Aspear Berry',        'price': 0},
	   {'id': 131, 'name': 'Leppa Berry',         'price': 0},
	   {'id': 132, 'name': 'Oran Berry',          'price': 0},
	   {'id': 133, 'name': 'Persim Berry',        'price': 0},
	   {'id': 134, 'name': 'Lum Berry',           'price': 0},
	   {'id': 135, 'name': 'Sitrus Berry',        'price': 0},
	   {'id': 136, 'name': 'Figy Berry',          'price': 0},
	   {'id': 137, 'name': 'Wiki Berry',          'price': 0},
	   {'id': 138, 'name': 'Mago Berry',          'price': 0},
	   {'id': 139, 'name': 'Aguav Berry',         'price': 0},
	   {'id': 140, 'name': 'Iapapa Berry',        'price': 0},
	   {'id': 141, 'name': 'Razz Berry',          'price': 0},
	   {'id': 142, 'name': 'Bluk Berry',          'price': 0},
	   {'id': 143, 'name': 'Nanab Berry',         'price': 0},
	   {'id': 144, 'name': 'Wepear Berry',        'price': 0},
	   {'id': 145, 'name': 'Pinap Berry',         'price': 0},
	   {'id': 146, 'name': 'Pomeg Berry',         'price': 0},
	   {'id': 147, 'name': 'Kelpsy Berry',        'price': 0},
	   {'id': 148, 'name': 'Qualot Berry',        'price': 0},
	   {'id': 149, 'name': 'Hondew Berry',        'price': 0},
	   {'id': 150, 'name': 'Grepa Berry',         'price': 0},
	   {'id': 151, 'name': 'Tamato Berry',        'price': 0},
	   {'id': 152, 'name': 'Cornn Berry',         'price': 0},
	   {'id': 153, 'name': 'Magost Berry',        'price': 0},
	   {'id': 154, 'name': 'Rabuta Berry',        'price': 0},
	   {'id': 155, 'name': 'Nomel Berry',         'price': 0},
	   {'id': 156, 'name': 'Spelon Berry',        'price': 0},
	   {'id': 157, 'name': 'Pamtre Berry',        'price': 0},
	   {'id': 158, 'name': 'Watmel Berry',        'price': 0},
	   {'id': 159, 'name': 'Durin Berry',         'price': 0},
	   {'id': 160, 'name': 'Belue Berry',         'price': 0},
	   {'id': 161, 'name': 'Occa Berry',          'price': 0},
	   {'id': 162, 'name': 'Passho Berry',        'price': 0},
	   {'id': 163, 'name': 'Wacan Berry',         'price': 0},
	   {'id': 164, 'name': 'Rindo Berry',         'price': 0},
	   {'id': 165, 'name': 'Yache Berry',         'price': 0},
	   {'id': 166, 'name': 'Chople Berry',        'price': 0},
	   {'id': 167, 'name': 'Kebia Berry',         'price': 0},
	   {'id': 168, 'name': 'Shuca Berry',         'price': 0},
	   {'id': 169, 'name': 'Coba Berry',          'price': 0},
	   {'id': 170, 'name': 'Payapa Berry',        'price': 0},
	   {'id': 171, 'name': 'Tanga Berry',         'price': 0},
	   {'id': 172, 'name': 'Charti Berry',        'price': 0},
	   {'id': 173, 'name': 'Kasib Berry',         'price': 0},
	   {'id': 174, 'name': 'Haban Berry',         'price': 0},
	   {'id': 175, 'name': 'Colbur Berry',        'price': 0},
	   {'id': 176, 'name': 'Babiri Berry',        'price': 0},
	   {'id': 177, 'name': 'Chilan Berry',        'price': 0},
	   {'id': 178, 'name': 'Liechi Berry',        'price': 0},
	   {'id': 179, 'name': 'Ganlon Berry',        'price': 0},
	   {'id': 180, 'name': 'Salac Berry',         'price': 0},
	   {'id': 181, 'name': 'Petaya Berry',        'price': 0},
	   {'id': 182, 'name': 'Apicot Berry',        'price': 0},
	   {'id': 183, 'name': 'Lansat Berry',        'price': 0},
	   {'id': 184, 'name': 'Starf Berry',         'price': 0},
	   {'id': 185, 'name': 'Enigma Berry',        'price': 0},
	   {'id': 186, 'name': 'Micle Berry',         'price': 0},
	   {'id': 187, 'name': 'Custap Berry',        'price': 0},
	   {'id': 188, 'name': 'Jaboca Berry',        'price': 0},
	   {'id': 189, 'name': 'Rowap Berry',         'price': 0},
	   {'id': 190, 'name': 'Bright Powder',       'price': 0},
	   {'id': 191, 'name': 'White Herb',          'price': 0},
	   {'id': 192, 'name': 'Macho Brace',         'price': 0},
	   {'id': 193, 'name': 'Exp. Share',          'price': 0},
	   {'id': 194, 'name': 'Quick Claw',          'price': 0},
	   {'id': 195, 'name': 'Soothe Bell',         'price': 0},
	   {'id': 196, 'name': 'Mental Herb',         'price': 0},
	   {'id': 197, 'name': 'Choice Band',         'price': 0},
	   {'id': 198, 'name': 'Kings Rock',          'price': 0},
	   {'id': 199, 'name': 'Silver Powder',       'price': 0},
	   {'id': 200, 'name': 'Amulet Coin',         'price': 0},
	   {'id': 201, 'name': 'Cleanse Tag',         'price': 0},
	   {'id': 202, 'name': 'Soul Dew',            'price': 0},
	   {'id': 203, 'name': 'Deep Sea Tooth',      'price': 0},
	   {'id': 204, 'name': 'Deep Sea Scale',      'price': 0},
	   {'id': 205, 'name': 'Smoke Ball',          'price': 0},
	   {'id': 206, 'name': 'Everstone',           'price': 0},
	   {'id': 207, 'name': 'Focus Band',          'price': 0},
	   {'id': 208, 'name': 'Lucky Egg',           'price': 0},
	   {'id': 209, 'name': 'Scope Lens',          'price': 0},
	   {'id': 210, 'name': 'Metal Coat',          'price': 0},
	   {'id': 211, 'name': 'Leftovers',           'price': 0},
	   {'id': 212, 'name': 'Dragon Scale',        'price': 0},
	   {'id': 213, 'name': 'Light Ball',          'price': 0},
	   {'id': 214, 'name': 'Soft Sand',           'price': 0},
	   {'id': 215, 'name': 'Hard Stone',          'price': 0},
	   {'id': 216, 'name': 'Miracle Seed',        'price': 0},
	   {'id': 217, 'name': 'Black Glasses',       'price': 0},
	   {'id': 218, 'name': 'Black Belt',          'price': 0},
	   {'id': 219, 'name': 'Magnet',              'price': 0},
	   {'id': 220, 'name': 'Mystic Water',        'price': 0},
	   {'id': 221, 'name': 'Sharp Beak',          'price': 0},
	   {'id': 222, 'name': 'Poison Barb',         'price': 0},
	   {'id': 223, 'name': 'Never-Melt Ice',      'price': 0},
	   {'id': 224, 'name': 'Spell Tag',           'price': 0},
	   {'id': 225, 'name': 'Twisted Spoon',       'price': 0},
	   {'id': 226, 'name': 'Charcoal',            'price': 0},
	   {'id': 227, 'name': 'Dragon Fang',         'price': 0},
	   {'id': 228, 'name': 'Silk Scarf',          'price': 0},
	   {'id': 229, 'name': 'Up-Grade',            'price': 0},
	   {'id': 230, 'name': 'Shell Bell',          'price': 0},
	   {'id': 231, 'name': 'Sea Incense',         'price': 0},
	   {'id': 232, 'name': 'Lax Incense',         'price': 0},
	   {'id': 233, 'name': 'Lucky Punch',         'price': 0},
	   {'id': 234, 'name': 'Metal Powder',        'price': 0},
	   {'id': 235, 'name': 'Thick Club',          'price': 0},
	   {'id': 236, 'name': 'Stick',               'price': 0},
	   {'id': 237, 'name': 'Red Scarf',           'price': 0},
	   {'id': 238, 'name': 'Blue Scarf',          'price': 0},
	   {'id': 239, 'name': 'Pink Scarf',          'price': 0},
	   {'id': 240, 'name': 'Green Scarf',         'price': 0},
	   {'id': 241, 'name': 'Yellow Scarf',        'price': 0},
	   {'id': 242, 'name': 'Wide Lens',           'price': 0},
	   {'id': 243, 'name': 'Muscle Band',         'price': 0},
	   {'id': 244, 'name': 'Wise Glasses',        'price': 0},
	   {'id': 245, 'name': 'Expert Belt',         'price': 0},
	   {'id': 246, 'name': 'Light Clay',          'price': 0},
	   {'id': 247, 'name': 'Life Orb',            'price': 0},
	   {'id': 248, 'name': 'Power Herb',          'price': 0},
	   {'id': 249, 'name': 'Toxic Orb',           'price': 0},
	   {'id': 250, 'name': 'Flame Orb',           'price': 0},
	   {'id': 251, 'name': 'Quick Powder',        'price': 0},
	   {'id': 252, 'name': 'Focus Sash',          'price': 0},
	   {'id': 253, 'name': 'Zoom Lens',           'price': 0},
	   {'id': 254, 'name': 'Metronome',           'price': 0},
	   {'id': 255, 'name': 'Iron Ball',           'price': 0},
	   {'id': 256, 'name': 'Lagging Tail',        'price': 0},
	   {'id': 257, 'name': 'Destiny Knot',        'price': 0},
	   {'id': 258, 'name': 'Black Sludge',        'price': 0},
	   {'id': 259, 'name': 'Icy Rock',            'price': 0},
	   {'id': 260, 'name': 'Smooth Rock',         'price': 0},
	   {'id': 261, 'name': 'Heat Rock',           'price': 0},
	   {'id': 262, 'name': 'Damp Rock',           'price': 0},
	   {'id': 263, 'name': 'Grip Claw',           'price': 0},
	   {'id': 264, 'name': 'Choice Scarf',        'price': 0},
	   {'id': 265, 'name': 'Sticky Barb',         'price': 0},
	   {'id': 266, 'name': 'Power Bracer',        'price': 0},
	   {'id': 267, 'name': 'Power Belt',          'price': 0},
	   {'id': 268, 'name': 'Power Lens',          'price': 0},
	   {'id': 269, 'name': 'Power Band',          'price': 0},
	   {'id': 270, 'name': 'Power Anklet',        'price': 0},
	   {'id': 271, 'name': 'Power Weight',        'price': 0},
	   {'id': 272, 'name': 'Shed Shell',          'price': 0},
	   {'id': 273, 'name': 'Big Root',            'price': 0},
	   {'id': 274, 'name': 'Choice Specs',        'price': 0},
	   {'id': 275, 'name': 'Flame Plate',         'price': 0},
	   {'id': 276, 'name': 'Splash Plate',        'price': 0},
	   {'id': 277, 'name': 'Zap Plate',           'price': 0},
	   {'id': 278, 'name': 'Meadow Plate',        'price': 0},
	   {'id': 279, 'name': 'Icicle Plate',        'price': 0},
	   {'id': 280, 'name': 'Fist Plate',          'price': 0},
	   {'id': 281, 'name': 'Toxic Plate',         'price': 0},
	   {'id': 282, 'name': 'Earth Plate',         'price': 0},
	   {'id': 283, 'name': 'Sky Plate',           'price': 0},
	   {'id': 284, 'name': 'Mind Plate',          'price': 0},
	   {'id': 285, 'name': 'Insect Plate',        'price': 0},
	   {'id': 286, 'name': 'Stone Plate',         'price': 0},
	   {'id': 287, 'name': 'Spooky Plate',        'price': 0},
	   {'id': 288, 'name': 'Draco Plate',         'price': 0},
	   {'id': 289, 'name': 'Dread Plate',         'price': 0},
	   {'id': 290, 'name': 'Iron Plate',          'price': 0},
	   {'id': 291, 'name': 'Odd Incense',         'price': 0},
	   {'id': 292, 'name': 'Rock Incense',        'price': 0},
	   {'id': 293, 'name': 'Full Incense',        'price': 0},
	   {'id': 294, 'name': 'Wave Incense',        'price': 0},
	   {'id': 295, 'name': 'Rose Incense',        'price': 0},
	   {'id': 296, 'name': 'Luck Incense',        'price': 0},
	   {'id': 297, 'name': 'Pure Incense',        'price': 0},
	   {'id': 298, 'name': 'Protector',           'price': 0},
	   {'id': 299, 'name': 'Electirizer',         'price': 0},
	   {'id': 300, 'name': 'Magmarizer',          'price': 0},
	   {'id': 301, 'name': 'Dubious Disc',        'price': 0},
	   {'id': 302, 'name': 'Reaper Cloth',        'price': 0},
	   {'id': 303, 'name': 'Razor Claw',          'price': 0},
	   {'id': 304, 'name': 'Razor Fang',          'price': 0},
	   {'id': 305, 'name': 'TM01',                'price': 0},
	   {'id': 306, 'name': 'TM02',                'price': 0},
	   {'id': 307, 'name': 'TM03',                'price': 0},
	   {'id': 308, 'name': 'TM04',                'price': 0},
	   {'id': 309, 'name': 'TM05',                'price': 0},
	   {'id': 310, 'name': 'TM06',                'price': 0},
	   {'id': 311, 'name': 'TM07',                'price': 0},
	   {'id': 312, 'name': 'TM08',                'price': 0},
	   {'id': 313, 'name': 'TM09',                'price': 0},
	   {'id': 314, 'name': 'TM10',                'price': 0},
	   {'id': 315, 'name': 'TM11',                'price': 0},
	   {'id': 316, 'name': 'TM12',                'price': 0},
	   {'id': 317, 'name': 'TM13',                'price': 0},
	   {'id': 318, 'name': 'TM14',                'price': 0},
	   {'id': 319, 'name': 'TM15',                'price': 0},
	   {'id': 320, 'name': 'TM16',                'price': 0},
	   {'id': 321, 'name': 'TM17',                'price': 0},
	   {'id': 322, 'name': 'TM18',                'price': 0},
	   {'id': 323, 'name': 'TM19',                'price': 0},
	   {'id': 324, 'name': 'TM20',                'price': 0},
	   {'id': 325, 'name': 'TM21',                'price': 0},
	   {'id': 326, 'name': 'TM22',                'price': 0},
	   {'id': 327, 'name': 'TM23',                'price': 0},
	   {'id': 328, 'name': 'TM24',                'price': 0},
	   {'id': 329, 'name': 'TM25',                'price': 0},
	   {'id': 330, 'name': 'TM26',                'price': 0},
	   {'id': 331, 'name': 'TM27',                'price': 0},
	   {'id': 332, 'name': 'TM28',                'price': 0},
	   {'id': 333, 'name': 'TM29',                'price': 0},
	   {'id': 334, 'name': 'TM30',                'price': 0},
	   {'id': 335, 'name': 'TM31',                'price': 0},
	   {'id': 336, 'name': 'TM32',                'price': 0},
	   {'id': 337, 'name': 'TM33',                'price': 0},
	   {'id': 338, 'name': 'TM34',                'price': 0},
	   {'id': 339, 'name': 'TM35',                'price': 0},
	   {'id': 340, 'name': 'TM36',                'price': 0},
	   {'id': 341, 'name': 'TM37',                'price': 0},
	   {'id': 342, 'name': 'TM38',                'price': 0},
	   {'id': 343, 'name': 'TM39',                'price': 0},
	   {'id': 344, 'name': 'TM40',                'price': 0},
	   {'id': 345, 'name': 'TM41',                'price': 0},
	   {'id': 346, 'name': 'TM42',                'price': 0},
	   {'id': 347, 'name': 'TM43',                'price': 0},
	   {'id': 348, 'name': 'TM44',                'price': 0},
	   {'id': 349, 'name': 'TM45',                'price': 0},
	   {'id': 350, 'name': 'TM46',                'price': 0},
	   {'id': 351, 'name': 'TM47',                'price': 0},
	   {'id': 352, 'name': 'TM48',                'price': 0},
	   {'id': 353, 'name': 'TM49',                'price': 0},
	   {'id': 354, 'name': 'TM50',                'price': 0},
	   {'id': 355, 'name': 'TM51',                'price': 0},
	   {'id': 356, 'name': 'TM52',                'price': 0},
	   {'id': 357, 'name': 'TM53',                'price': 0},
	   {'id': 358, 'name': 'TM54',                'price': 0},
	   {'id': 359, 'name': 'TM55',                'price': 0},
	   {'id': 360, 'name': 'TM56',                'price': 0},
	   {'id': 361, 'name': 'TM57',                'price': 0},
	   {'id': 362, 'name': 'TM58',                'price': 0},
	   {'id': 363, 'name': 'TM59',                'price': 0},
	   {'id': 364, 'name': 'TM60',                'price': 0},
	   {'id': 365, 'name': 'TM61',                'price': 0},
	   {'id': 366, 'name': 'TM62',                'price': 0},
	   {'id': 367, 'name': 'TM63',                'price': 0},
	   {'id': 368, 'name': 'TM64',                'price': 0},
	   {'id': 369, 'name': 'TM65',                'price': 0},
	   {'id': 370, 'name': 'TM66',                'price': 0},
	   {'id': 371, 'name': 'TM67',                'price': 0},
	   {'id': 372, 'name': 'TM68',                'price': 0},
	   {'id': 373, 'name': 'TM69',                'price': 0},
	   {'id': 374, 'name': 'TM70',                'price': 0},
	   {'id': 375, 'name': 'TM71',                'price': 0},
	   {'id': 376, 'name': 'TM72',                'price': 0},
	   {'id': 377, 'name': 'TM73',                'price': 0},
	   {'id': 378, 'name': 'TM74',                'price': 0},
	   {'id': 379, 'name': 'TM75',                'price': 0},
	   {'id': 380, 'name': 'TM76',                'price': 0},
	   {'id': 381, 'name': 'TM77',                'price': 0},
	   {'id': 382, 'name': 'TM78',                'price': 0},
	   {'id': 383, 'name': 'TM79',                'price': 0},
	   {'id': 384, 'name': 'TM80',                'price': 0},
	   {'id': 385, 'name': 'TM81',                'price': 0},
	   {'id': 386, 'name': 'TM82',                'price': 0},
	   {'id': 387, 'name': 'TM83',                'price': 0},
	   {'id': 388, 'name': 'TM84',                'price': 0},
	   {'id': 389, 'name': 'TM85',                'price': 0},
	   {'id': 390, 'name': 'TM86',                'price': 0},
	   {'id': 391, 'name': 'TM87',                'price': 0},
	   {'id': 392, 'name': 'TM88',                'price': 0},
	   {'id': 393, 'name': 'TM89',                'price': 0},
	   {'id': 394, 'name': 'TM90',                'price': 0},
	   {'id': 395, 'name': 'TM91',                'price': 0},
	   {'id': 396, 'name': 'TM92',                'price': 0},
	   {'id': 442, 'name': 'Griseous Orb',        'price': 0},
	   {'id': 449, 'name': 'Lure Ball',           'price': 0},
	   {'id': 450, 'name': 'Level Ball',          'price': 0},
	   {'id': 451, 'name': 'Moon Ball',           'price': 0},
	   {'id': 452, 'name': 'Heavy Ball',          'price': 0},
	   {'id': 453, 'name': 'Fast Ball',           'price': 0},
	   {'id': 454, 'name': 'Friend Ball',         'price': 0},
	   {'id': 455, 'name': 'Love Ball',           'price': 0},
	   {'id': 515, 'name': 'Orange Mail',         'price': 0},
	   {'id': 516, 'name': 'Harbor Mail',         'price': 0},
	   {'id': 517, 'name': 'Glitter Mail',        'price': 0},
	   {'id': 518, 'name': 'Mech Mail',           'price': 0},
	   {'id': 519, 'name': 'Wood Mail',           'price': 0},
	   {'id': 520, 'name': 'Wave Mail',           'price': 0},
	   {'id': 521, 'name': 'Bead Mail',           'price': 0},
	   {'id': 522, 'name': 'Shadow Mail',         'price': 0},
	   {'id': 523, 'name': 'Tropic Mail',         'price': 0},
	   {'id': 524, 'name': 'Dream Mail',          'price': 0},
	   {'id': 525, 'name': 'Fab Mail',            'price': 0},
	   {'id': 563, 'name': 'Douse Drive',         'price': 0},
	   {'id': 564, 'name': 'Shock Drive',         'price': 0},
	   {'id': 565, 'name': 'Burn Drive',          'price': 0},
	   {'id': 566, 'name': 'Chill Drive',         'price': 0},
	   {'id': 567, 'name': 'Sweet Heart',         'price': 0},
	   {'id': 568, 'name': 'Greet Mail',          'price': 0},
	   {'id': 569, 'name': 'Favored Mail',        'price': 0},
	   {'id': 570, 'name': 'RSVP Mail',           'price': 0},
	   {'id': 571, 'name': 'Thanks Mail',         'price': 0},
	   {'id': 572, 'name': 'Inquiry Mail',        'price': 0},
	   {'id': 573, 'name': 'Like Mail',           'price': 0},
	   {'id': 574, 'name': 'Reply Mail',          'price': 0},
	   {'id': 575, 'name': 'Bridge Mail S',       'price': 0},
	   {'id': 576, 'name': 'Bridge Mail D',       'price': 0},
	   {'id': 577, 'name': 'Bridge Mail T',       'price': 0},
	   {'id': 578, 'name': 'Bridge Mail V',       'price': 0},
	   {'id': 579, 'name': 'Bridge Mail M',       'price': 0},
	   {'id': 580, 'name': 'Prism Scale',         'price': 0},
	   {'id': 581, 'name': 'Eviolite',            'price': 0},
	   {'id': 582, 'name': 'Float Stone',         'price': 0},
	   {'id': 583, 'name': 'Rocky Helmet',        'price': 0},
	   {'id': 584, 'name': 'Air Balloon',         'price': 0},
	   {'id': 585, 'name': 'Red Card',            'price': 0},
	   {'id': 586, 'name': 'Ring Target',         'price': 0},
	   {'id': 587, 'name': 'Binding Band',        'price': 0},
	   {'id': 588, 'name': 'Absorb Bulb',         'price': 0},
	   {'id': 589, 'name': 'Cell Battery',        'price': 0},
	   {'id': 590, 'name': 'Eject Button',        'price': 0},
	   {'id': 591, 'name': 'Fire Gem',            'price': 0},
	   {'id': 592, 'name': 'Water Gem',           'price': 0},
	   {'id': 593, 'name': 'Electric Gem',        'price': 0},
	   {'id': 594, 'name': 'Grass Gem',           'price': 0},
	   {'id': 595, 'name': 'Ice Gem',             'price': 0},
	   {'id': 596, 'name': 'Fighting Gem',        'price': 0},
	   {'id': 597, 'name': 'Poison Gem',          'price': 0},
	   {'id': 598, 'name': 'Ground Gem',          'price': 0},
	   {'id': 599, 'name': 'Flying Gem',          'price': 0},
	   {'id': 600, 'name': 'Psychic Gem',         'price': 0},
	   {'id': 601, 'name': 'Bug Gem',             'price': 0},
	   {'id': 602, 'name': 'Rock Gem',            'price': 0},
	   {'id': 603, 'name': 'Ghost Gem',           'price': 0},
	   {'id': 604, 'name': 'Dark Gem',            'price': 0},
	   {'id': 605, 'name': 'Steel Gem',           'price': 0},
	   {'id': 606, 'name': 'Health Wing',         'price': 0},
	   {'id': 607, 'name': 'Muscle Wing',         'price': 0},
	   {'id': 608, 'name': 'Resist Wing',         'price': 0},
	   {'id': 609, 'name': 'Genius Wing',         'price': 0},
	   {'id': 610, 'name': 'Clever Wing',         'price': 0},
	   {'id': 611, 'name': 'Swift Wing',          'price': 0},
	   {'id': 612, 'name': 'Pretty Wing',         'price': 0},
	   {'id': 613, 'name': 'Cover Fossil',        'price': 0},
	   {'id': 614, 'name': 'Plume Fossil',        'price': 0},
	   {'id': 616, 'name': 'Pass Orb',            'price': 0},
	   {'id': 618, 'name': 'Poke Toy',            'price': 0},
	   {'id': 632, 'name': 'Casteliacone',        'price': 0},
	   {'id': 659, 'name': 'TM93',                'price': 0},
	   {'id': 660, 'name': 'TM94',                'price': 0},
	   {'id': 661, 'name': 'TM95',                'price': 0},
	   {'id': 668, 'name': 'Dragon Gem',          'price': 0},
	   {'id': 669, 'name': 'Normal Gem',          'price': 0},
	   {'id': 768, 'name': 'No Experience Stone', 'price': 0},
	   {'id': 811, 'name': 'Ice Stone',           'price': 8000},
	   {'id': 812, 'name': 'Moss Stone',          'price': 8000},
	];
};
